@echo off
REM Build script for GRID Launcher
REM This script builds the application into a standalone Windows executable

echo.
echo ================================
echo GRID Launcher Build Script
echo ================================
echo.

REM Check if virtual environment exists
if not exist ".venv\Scripts\activate.bat" (
    echo ERROR: Virtual environment not found at .venv
    echo Please run: python -m venv .venv
    exit /b 1
)

REM Activate virtual environment
echo Activating virtual environment...
call .venv\Scripts\activate.bat

REM Install/check PyInstaller
echo Checking dependencies...
python -m pip list | findstr PyInstaller >nul
if errorlevel 1 (
    echo Installing PyInstaller...
    python -m pip install pyinstaller
)

REM Detect version from git and strip leading "v"
echo Detecting version from git...
for /f "delims=" %%i in ('git describe --tags --always --dirty 2^>nul') do set VERSION=%%i
if "%VERSION%"=="" set VERSION=0.0.0-dev
REM Strip leading "v" if present
if "%VERSION:~0,1%"=="v" set VERSION=%VERSION:~1%
echo Building version: %VERSION%

REM Generate grid_launcher\version.py
(
echo """Application version (generated by build.bat)."""
echo.
echo __version__ = "%VERSION%"
) > grid_launcher\version.py

REM Run PyInstaller
echo.
echo Building executable...
echo.

python -m PyInstaller ^
    --noconfirm ^
    --clean ^
    --windowed ^
    --onefile ^
    --name grid-launcher ^
    --add-data "assets;assets" ^
    --add-data "retroarch-core-list.json;." ^
    --add-data "romm-platform-cores.json;." ^
    --add-data "emulator-autoprofiles.json;." ^
    --hidden-import brotli ^
    --hidden-import pyzstd ^
    --hidden-import pyppmd ^
    --hidden-import keyring.backends.Windows ^
    grid-launcher.py

REM Check if build was successful
if %errorlevel% equ 0 (
    echo.
    echo ================================
    echo BUILD SUCCESSFUL!
    echo ================================
    echo.
    echo Executable location:
    echo   .\dist\grid-launcher.exe
    echo.
    echo You can now:
    echo   1. Run it directly: .\dist\grid-launcher.exe
    echo   2. Move it to any location
    echo   3. Share the executable file
) else (
    echo.
    echo BUILD FAILED
    echo Exit code: %errorlevel%
    exit /b %errorlevel%
)
