#!/usr/bin/env bash
# Build script for GRID Launcher
# This script builds the application into a standalone Linux executable

echo ""
echo "================================"
echo "GRID Launcher Build Script"
echo "================================"
echo ""

# Build targets: default is the standalone onefile binary; --appimage adds an AppImage.
# Multiple targets can be combined, e.g. ./build.sh --onefile --appimage
BUILD_TARGETS=()

print_help() {
    cat <<EOF
Usage: ./build.sh [targets...]

Targets:
  --onefile    Build a standalone onefile executable (default)
  --appimage   Build an AppImage package

Multiple targets can be combined and are built sequentially, e.g.:
  ./build.sh --onefile --appimage

Options:
  --help, -h   Show this help message
EOF
}

for arg in "$@"; do
    case "$arg" in
        --onefile)
            BUILD_TARGETS+=("onefile")
            ;;
        --appimage)
            BUILD_TARGETS+=("appimage")
            ;;
        --windows)
            echo "ERROR: --windows is not supported by build.sh (Linux build script)."
            echo "Use build.bat or build.ps1 on Windows instead."
            exit 1
            ;;
        --help|-h)
            print_help
            exit 0
            ;;
        *)
            echo "ERROR: Unknown flag '$arg'"
            echo ""
            print_help
            exit 1
            ;;
    esac
done

# Default to onefile for backward compatibility when no target is specified.
if [ ${#BUILD_TARGETS[@]} -eq 0 ]; then
    BUILD_TARGETS=("onefile")
fi

# Deduplicate targets while preserving first-seen order.
DEDUP_TARGETS=()
for target in "${BUILD_TARGETS[@]}"; do
    seen=0
    for existing in "${DEDUP_TARGETS[@]}"; do
        if [ "$existing" = "$target" ]; then
            seen=1
            break
        fi
    done
    if [ $seen -eq 0 ]; then
        DEDUP_TARGETS+=("$target")
    fi
done
BUILD_TARGETS=("${DEDUP_TARGETS[@]}")

# Build AppImage before onefile so both outputs coexist in dist/
# (onefile's --clean would otherwise wipe the AppImage's onedir output).
ORDERED_TARGETS=()
for target in "${BUILD_TARGETS[@]}"; do
    if [ "$target" = "appimage" ]; then
        ORDERED_TARGETS+=("$target")
    fi
done
for target in "${BUILD_TARGETS[@]}"; do
    if [ "$target" = "onefile" ]; then
        ORDERED_TARGETS+=("$target")
    fi
done
BUILD_TARGETS=("${ORDERED_TARGETS[@]}")

# Detect version from git and strip a leading "v" (e.g. v0.7.0 -> 0.7.0).
VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "0.0.0-dev")
VERSION="${VERSION#v}"
echo "Building version: $VERSION"

# Generate grid_launcher/version.py so the bundled app reports the right version.
cat > grid_launcher/version.py <<EOF
"""Application version (generated by build.sh)."""

__version__ = "$VERSION"
EOF


# pygame 2.6.1 has no Python 3.14 wheel — build requires Python 3.12 or 3.13.
BUILD_PYTHON=$(command -v python3.12 || command -v python3.13)
if [ -z "$BUILD_PYTHON" ]; then
    echo "ERROR: Python 3.12 or 3.13 is required to build (pygame has no 3.14 wheel)"
    echo "Install with: sudo dnf install python3.12  # or python3.13"
    exit 1
fi

# Recreate the venv if it is missing or was built with the wrong Python.
VENV_PYTHON=".venv/bin/python"
if [ -f "$VENV_PYTHON" ]; then
    VENV_VER=$("$VENV_PYTHON" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
    BUILD_VER=$("$BUILD_PYTHON" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
    if [ "$VENV_VER" != "$BUILD_VER" ]; then
        echo "Venv Python ($VENV_VER) does not match build Python ($BUILD_VER) — recreating venv..."
        rm -rf .venv
    fi
fi
if [ ! -f "$VENV_PYTHON" ]; then
    echo "Creating virtual environment with $("$BUILD_PYTHON" --version)..."
    "$BUILD_PYTHON" -m venv .venv
fi

# Use the venv's pip/python directly — avoids activation edge cases.
VENV_PIP=".venv/bin/pip"
VENV_PYTHON=".venv/bin/python"

# Install app dependencies + PyInstaller into the venv.
echo "Activating virtual environment..."
echo "Checking dependencies..."
"$VENV_PIP" install -r requirements.txt
"$VENV_PIP" install pyinstaller

# Build the AppImage package. Returns the build exit code.
build_appimage() {
    # Run PyInstaller in onedir mode for AppImage packaging
    echo ""
    echo "Building AppImage..."
    echo ""

    # --windowed is a no-op on Linux (PyInstaller will print a harmless warning); kept for CLI consistency with the Windows scripts
    "$VENV_PYTHON" -m PyInstaller \
        --noconfirm \
        --clean \
        --windowed \
        --onedir \
        --name grid-launcher \
        --add-data "assets:assets" \
        --add-data "retroarch-core-list.json:." \
        --add-data "romm-platform-cores.json:." \
        --add-data "emulator-autoprofiles.json:." \
        --hidden-import brotli \
        --hidden-import pyzstd \
        --hidden-import pyppmd \
        --hidden-import keyring.backends.SecretService \
        --hidden-import keyring.backends.kwallet \
        grid-launcher.py

    local exit_code=$?

    if [ $exit_code -ne 0 ]; then
        echo ""
        echo "AppImage build FAILED (PyInstaller)"
        echo "Exit code: $exit_code"
        return $exit_code
    fi

    # Rasterize the app icon (requires rsvg-convert from librsvg2-bin)
    echo ""
    echo "Rasterizing app icon..."
    if ! command -v rsvg-convert >/dev/null 2>&1; then
        echo "ERROR: rsvg-convert is required to rasterize the app icon"
        echo "Install with: sudo dnf install librsvg2-tools  # or: sudo apt install librsvg2-bin"
        return 1
    fi
    rsvg-convert -w 256 -h 256 \
        assets/svg/io.github.Sixdd6.GRIDLauncher.svg \
        -o appimage/grid-launcher.png
    if [ ! -f appimage/grid-launcher.png ]; then
        echo "ERROR: icon rasterization failed — appimage/grid-launcher.png was not produced"
        return 1
    fi

    # Assemble AppDir
    echo "Assembling AppDir..."
    rm -rf AppDir
    mkdir -p AppDir/usr/bin
    cp -r dist/grid-launcher/* AppDir/usr/bin/
    cp appimage/AppRun AppDir/AppRun
    chmod +x AppDir/AppRun
    cp appimage/grid-launcher.desktop AppDir/grid-launcher.desktop
    # Substitute the version placeholder before appimagetool reads the desktop file.
    sed -i "s/%GRIDLAUNCHER_VERSION%/$VERSION/g" AppDir/grid-launcher.desktop
    cp appimage/grid-launcher.png AppDir/grid-launcher.png

    # Download appimagetool if it isn't already present
    if [ ! -x "./appimagetool" ]; then
        echo "Downloading appimagetool..."
        wget -q -O appimagetool \
            "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
        chmod +x appimagetool
    fi

    # Build the AppImage
    echo "Building AppImage..."
    mkdir -p dist
    local output_name="grid-launcher-${VERSION}-x86_64.AppImage"
    ./appimagetool --appimage-extract-and-run AppDir "dist/$output_name"
    exit_code=$?

    if [ $exit_code -eq 0 ]; then
        echo ""
        echo "AppImage build successful!"
        echo "  ./dist/$output_name"
    else
        echo ""
        echo "AppImage build FAILED (appimagetool)"
        echo "Exit code: $exit_code"
    fi

    return $exit_code
}

# Build the standalone onefile executable. Returns the build exit code.
build_onefile() {
    # Run PyInstaller
    echo ""
    echo "Building executable..."
    echo ""

    # --windowed is a no-op on Linux (PyInstaller will print a harmless warning); kept for CLI consistency with the Windows scripts
    "$VENV_PYTHON" -m PyInstaller \
        --noconfirm \
        --clean \
        --windowed \
        --onefile \
        --name grid-launcher \
        --add-data "assets:assets" \
        --add-data "retroarch-core-list.json:." \
        --add-data "romm-platform-cores.json:." \
        --add-data "emulator-autoprofiles.json:." \
        --hidden-import brotli \
        --hidden-import pyzstd \
        --hidden-import pyppmd \
        --hidden-import keyring.backends.SecretService \
        --hidden-import keyring.backends.kwallet \
        grid-launcher.py

    local exit_code=$?

    if [ $exit_code -eq 0 ]; then
        echo ""
        echo "Onefile build successful!"
        echo "  ./dist/grid-launcher"
    else
        echo ""
        echo "Onefile build FAILED (PyInstaller)"
        echo "Exit code: $exit_code"
    fi

    return $exit_code
}

# Build each requested target sequentially, tracking failures.
OVERALL_EXIT_CODE=0
BUILT_TARGETS=()
FAILED_TARGETS=()

for target in "${BUILD_TARGETS[@]}"; do
    case "$target" in
        appimage)
            build_appimage
            ;;
        onefile)
            build_onefile
            ;;
    esac
    if [ $? -eq 0 ]; then
        BUILT_TARGETS+=("$target")
    else
        FAILED_TARGETS+=("$target")
        OVERALL_EXIT_CODE=1
    fi
done

echo ""
echo "================================"
if [ $OVERALL_EXIT_CODE -eq 0 ]; then
    echo "BUILD SUCCESSFUL!"
else
    echo "BUILD FINISHED WITH FAILURES"
fi
echo "================================"
echo ""

if [ ${#BUILT_TARGETS[@]} -gt 0 ]; then
    echo "Succeeded: ${BUILT_TARGETS[*]}"
fi
if [ ${#FAILED_TARGETS[@]} -gt 0 ]; then
    echo "Failed:    ${FAILED_TARGETS[*]}"
fi

exit $OVERALL_EXIT_CODE
