name: Build Linux

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    name: Build with PyInstaller
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller PySide6

      - name: Build executable
        run: |
          pyinstaller --noconfirm --clean --windowed --onefile --name rom-mate-neo --add-data "assets:assets" --add-data "retroarch-core-list.json:." --add-data "emulator-autoprofiles.json:." rom-mate.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rom-mate-neo-linux
          path: dist/rom-mate-neo
          if-no-files-found: error

      - name: Attach binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/rom-mate-neo
